name: fullstack-application

on:
  push:
    branches: [ "main", "feedback-implementation" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run test coverage
        run: npm run test --coverage
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: 
            echo " ${{ secrets.ENV }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build the docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-store-application:v1 .

      - name: Run the container
        run: docker run -d ${{ secrets.DOCKER_USERNAME }}/book-store-application:v1 

      - name: Display containers
        run: docker ps -a

      - name: Display images
        run: docker images
        
      - name: push the docker-image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/book-store-application:v1


 

     
